### ISSUE TITLE
Addition of jokes when the user stars the repo.

### ISSUE THREAD

**Issue by harshith-venkatesh** [DheerajMahra/star-to-joke#1]
- Currently it looks like the joke is replaced when user stars the repo.
- A way to append the jokes instead could be a new way to look into
- Would it be good to have list of people who have starred the repo as well

**Comment by DheerajMahra** [comment]
Hey @harshith-venkatesh , thanks for trying out this project. 😃

- the jokes api that I am using has limited jokes, so appending the jokes would result in duplicacy in the readme.
- A list of stargazers is a good point, will incorporate it soon

**Comment by DheerajMahra** [comment]
Changes done #2 . Thanks to @deepakr-28 🙌
